# Generated by hardening pass.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_comment_id_alter_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='app_userpro_role_04109c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['department'], name='app_userpro_departm_2e0f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['graduation_year'], name='app_userpro_graduat_ef92a8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='app_job_status_32e622_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='app_job_created_e6bfbc_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company'], name='app_job_company_4f8a33_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='uniq_job_application_per_user'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['applicant', 'status'], name='app_jobappl_applica_1ea1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job', 'status'], name='app_jobappl_job_id_87100c_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='app_post_created_b97e76_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(raised__gte=0), name='campaign_raised_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(condition=models.Q(donor_count__gte=0), name='campaign_donor_count_non_negative'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'campaign_type'], name='app_campaig_status_6ec5a6_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_at'], name='app_campaig_created_9f39d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(amount__gt=0), name='donation_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['campaign', 'status'], name='app_donatio_campaig_6f7d81_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor', 'created_at'], name='app_donatio_donor_i_6750db_idx'),
        ),
    ]

