# Generated by Django 5.2.6 on 2026-03-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_security_constraints_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='campaign',
            new_name='app_campaig_status_f7e088_idx',
            old_name='app_campaig_status_6ec5a6_idx',
        ),
        migrations.RenameIndex(
            model_name='campaign',
            new_name='app_campaig_created_3ace8a_idx',
            old_name='app_campaig_created_9f39d5_idx',
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='app_donatio_campaig_12fca6_idx',
            old_name='app_donatio_campaig_6f7d81_idx',
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='app_donatio_donor_i_7ca34e_idx',
            old_name='app_donatio_donor_i_6750db_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='app_job_status_f38a63_idx',
            old_name='app_job_status_32e622_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='app_job_created_851d9b_idx',
            old_name='app_job_created_e6bfbc_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='app_job_company_e44da0_idx',
            old_name='app_job_company_4f8a33_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='app_jobappl_applica_b9b52a_idx',
            old_name='app_jobappl_applica_1ea1fc_idx',
        ),
        migrations.RenameIndex(
            model_name='jobapplication',
            new_name='app_jobappl_job_id_c33d05_idx',
            old_name='app_jobappl_job_id_87100c_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='app_post_created_9d016a_idx',
            old_name='app_post_created_b97e76_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='app_userpro_role_59e0a2_idx',
            old_name='app_userpro_role_04109c_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='app_userpro_departm_1a23e8_idx',
            old_name='app_userpro_departm_2e0f1c_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='app_userpro_graduat_e2c6e9_idx',
            old_name='app_userpro_graduat_ef92a8_idx',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clubjoinrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clubmessage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='clubpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hiringdrive',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentorgoal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentoringrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentoringsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
